---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes #become root

  vars_files: # variáveis de ambiente (via arquivo)
    - vars/main.yml

  #vars: # variáveis de ambiente (direto)
    #- dbname: "db01"
    #- dbusername: "root"
    #- dbpassword: "devopsmaonamassa"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql