apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
  labels:
    app: mysql-app
    type: database
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    spec:
      containers:
        - name: mysql-container
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: geek
  replicas: 1