services:
  banco:
    container_name: banco2
    image: mysql:8
    ports:
      - "3600:3306"
    restart: always
    volumes:
      - docker_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
volumes:
  docker_mysql:
    external: true