services:
  banco:
    container_name: banco
    image: mysql:8
    ports:
      - "3600:3306"
    restart: always
    volumes:
      - docker_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: site