services:
  mysql:
    image: mysql:8
    container_name: banco
    ports:
      - '3600:3306'
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: estagiario
      MYSQL_PASSWORD: '12345'
      MYSQL_DATABASE: banco
    networks:
      - rede-site
    restart: on-failure
    volumes:
      - 'banco:/var/lib/mysql'
  wordpress:
    image: wordpress:latest
    container_name: site
    ports:
      - '80:80'
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: estagiario
      WORDPRESS_DB_NAME: banco
      WORDPRESS_DB_PASSWORD: '12345'
    depends_on: 
      - mysql
    networks:
      - rede-site
    restart: on-failure
networks:
  rede-site:
    driver: bridge
volumes:
  banco:
    external: true