apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
  labels:
    app: interface-app
    type: interface
spec:
  selector:
    matchLabels:
      type: interface
  template:
    metadata:
      name: interface-pod
      labels:
        app: interface-app
        type: interface
    spec:
      containers:
        - name: interface-container
          image: nginx
  replicas: 1